# Generated by Django 5.2 on 2025-04-27 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=500)),
                ('corpo', models.FileField(upload_to='uploads/noticias/%Y/%m/%d/')),
                ('capa_noticia', models.ImageField(upload_to='uploads/noticias/CAPAS/%Y/%m/%d/')),
                ('visivel', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoNaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='uploads/noticias/arquivos/')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='news.noticia')),
            ],
        ),
    ]
