# Generated by Django 5.2 on 2025-05-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='corpo',
            field=models.FileField(upload_to='uploads/noticias/noticias/%Y/%m/%d/'),
        ),
    ]
