# Generated by Django 5.2.1 on 2025-06-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.CharField(blank=True, help_text='Separe as tags por vírgula', max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
