# Generated by Django 5.1.7 on 2025-04-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_arquivonanoticia_arquivos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='capa_noticia',
            field=models.ImageField(upload_to='uploads/noticias/CAPAS/%Y/%m/%d/'),
        ),
    ]
