# Generated by Django 5.2 on 2025-04-27 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('like', models.IntegerField(blank=True, default=0, null=True)),
                ('dislike', models.IntegerField(blank=True, default=0, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.perfil')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.noticia')),
            ],
        ),
        migrations.CreateModel(
            name='GosteiComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comentario')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='GosteiResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.perfil')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('like', models.IntegerField(blank=True, default=0, null=True)),
                ('dislike', models.IntegerField(blank=True, default=0, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='base.perfil')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comentario')),
            ],
        ),
    ]
