# Generated by Django 5.1.7 on 2025-04-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_perfil_foto_de_perfil'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GosteiComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comentario')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='GosteiResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.perfil')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comentario')),
            ],
        ),
    ]
