<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoticiaModel',
            new_name='Noticia',
        ),
    ]
=======
# Generated by Django 5.1.7 on 2025-04-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoticiaModel',
            new_name='Noticia',
        ),
    ]
>>>>>>> 6dad46b28fb6462401944f0f9a31339fde9957db
