# Generated by Django 5.2 on 2025-04-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, upload_to='uploads/perfis'),
        ),
    ]
