# Generated by Django 5.1.7 on 2025-04-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_noticiamodel_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='capa_noticia',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
