<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_noticia_capa_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='capa_noticia',
            field=models.ImageField(blank=True, null=True, upload_to='Notícias .MD/CAPAS/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='noticia',
            field=models.FileField(blank=True, null=True, upload_to='Notícias .MD/%Y/%m/%d/'),
        ),
    ]
=======
# Generated by Django 5.1.7 on 2025-04-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_noticia_capa_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='capa_noticia',
            field=models.ImageField(blank=True, null=True, upload_to='Notícias .MD/CAPAS/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='noticia',
            field=models.FileField(blank=True, null=True, upload_to='Notícias .MD/%Y/%m/%d/'),
        ),
    ]
>>>>>>> 6dad46b28fb6462401944f0f9a31339fde9957db
