# Generated by Django 5.1.7 on 2025-04-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_noticia_autor_noticia_visivel_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
    ]
