<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_noticia_visivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='room',
            new_name='noticia',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagens_na_noticia',
            field=models.ImageField(blank=True, null=True, upload_to='static/Notícias .MD/image'),
        ),
    ]
=======
# Generated by Django 5.1.7 on 2025-04-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_noticia_visivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='room',
            new_name='noticia',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagens_na_noticia',
            field=models.ImageField(blank=True, null=True, upload_to='static/Notícias .MD/image'),
        ),
    ]
>>>>>>> 6dad46b28fb6462401944f0f9a31339fde9957db
