<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_room_mensagem_noticia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='noticia',
            new_name='corpo',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagens_na_noticia',
        ),
        migrations.AddField(
            model_name='noticia',
            name='arquivos_na_noticia',
            field=models.ImageField(blank=True, null=True, upload_to='static/Notícias .MD/imagem'),
        ),
    ]
=======
# Generated by Django 5.1.7 on 2025-04-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_room_mensagem_noticia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='noticia',
            new_name='corpo',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagens_na_noticia',
        ),
        migrations.AddField(
            model_name='noticia',
            name='arquivos_na_noticia',
            field=models.ImageField(blank=True, null=True, upload_to='static/Notícias .MD/imagem'),
        ),
    ]
>>>>>>> 6dad46b28fb6462401944f0f9a31339fde9957db
