<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_noticia_noticia_corpo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='arquivos_na_noticia',
            field=models.FileField(blank=True, null=True, upload_to='static/Notícias .MD/arquivos'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='capa_noticia',
            field=models.ImageField(upload_to='Notícias .MD/CAPAS/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='corpo',
            field=models.FileField(upload_to='Notícias .MD/%Y/%m/%d/'),
        ),
    ]
=======
# Generated by Django 5.1.7 on 2025-04-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_noticia_noticia_corpo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='arquivos_na_noticia',
            field=models.FileField(blank=True, null=True, upload_to='static/Notícias .MD/arquivos'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='capa_noticia',
            field=models.ImageField(upload_to='Notícias .MD/CAPAS/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='corpo',
            field=models.FileField(upload_to='Notícias .MD/%Y/%m/%d/'),
        ),
    ]
>>>>>>> 6dad46b28fb6462401944f0f9a31339fde9957db
