<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_arquivonanoticia_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivonanoticia',
            name='Nome_do_Arquivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
=======
# Generated by Django 5.1.7 on 2025-04-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_arquivonanoticia_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivonanoticia',
            name='Nome_do_Arquivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
>>>>>>> 6dad46b28fb6462401944f0f9a31339fde9957db
