# Generated by Django 5.1.7 on 2025-04-07 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_arquivonanoticia_nome_do_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivonanoticia',
            old_name='arquivo',
            new_name='arquivos',
        ),
    ]
