<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_arquivonanoticia_nome_do_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='dislike',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
=======
# Generated by Django 5.1.7 on 2025-04-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_arquivonanoticia_nome_do_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='dislike',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
>>>>>>> 6dad46b28fb6462401944f0f9a31339fde9957db
