# Generated by Django 5.1.7 on 2025-04-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_mensagem_dislike_mensagem_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='dislike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
