<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='pode_alterar_foto_de_perfil',
            field=models.BooleanField(default=True),
        ),
    ]
=======
# Generated by Django 5.1.7 on 2025-04-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='pode_alterar_foto_de_perfil',
            field=models.BooleanField(default=True),
        ),
    ]
>>>>>>> 6dad46b28fb6462401944f0f9a31339fde9957db
