<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-15 21:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_perfil_pode_alterar_foto_de_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensagem',
            new_name='Comentarios',
        ),
    ]
=======
# Generated by Django 5.1.7 on 2025-04-15 21:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_perfil_pode_alterar_foto_de_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensagem',
            new_name='Comentarios',
        ),
    ]
>>>>>>> 6dad46b28fb6462401944f0f9a31339fde9957db
