# Generated by Django 5.1.7 on 2025-04-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_rename_comentarios_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='user',
            new_name='autor',
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_de_perfil',
            field=models.ImageField(default='foto_de_perfis/default.jpg', upload_to=''),
        ),
    ]
