# Generated by Django 5.1.7 on 2025-04-20 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_comentario_autor_alter_comentario_noticia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.perfil'),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('like', models.IntegerField(blank=True, default=0, null=True)),
                ('dislike', models.IntegerField(blank=True, default=0, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='base.perfil')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='base.comentario')),
            ],
        ),
    ]
