# Generated by Django 5.1.7 on 2025-04-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_comentario_autor_resposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='noticia',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='autor',
        ),
        migrations.DeleteModel(
            name='ArquivoNaNoticia',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
