# Generated by Django 5.1.7 on 2025-04-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_comentario_autor_remove_comentario_noticia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_de_perfil',
            field=models.ImageField(upload_to='uploads/perfis'),
        ),
    ]
